[tool.poetry]
name = "gittraining"
version = "0.1.0"
description = ""
authors = ["tetyana.peterburgska <tetyana.peterburgska@now-gmbh.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

